# Generated by Django migration
from django.db import migrations


def create_test_users(apps, schema_editor):
    User = apps.get_model('core', 'User')
    
    # Create first test user
    if not User.objects.filter(username='user1').exists():
        User.objects.create_user(
            username='user1',
            email='user1@example.com',
            password='solarvillage1',
            first_name='Test',
            last_name='User One',
        )
    
    # Create second test user
    if not User.objects.filter(username='user2').exists():
        User.objects.create_user(
            username='user2',
            email='user2@example.com',
            password='solarvillage2',
            first_name='Test',
            last_name='User Two',
        )


def remove_test_users(apps, schema_editor):
    User = apps.get_model('core', 'User')
    User.objects.filter(username__in=['user1', 'user2']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_test_users, remove_test_users),
    ]

