# Generated by Django 5.2.7 on 2025-11-09 01:13

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_test_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('FOOD_PANTRY', 'Food Pantry')], help_text='Type of community resource', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('hours', models.TextField(blank=True, help_text='Operating hours information')),
                ('eligibility_requirements', models.TextField(blank=True, help_text='Eligibility requirements for this resource')),
                ('services', models.TextField(blank=True, help_text='Additional services offered')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this resource is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Community Resources',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['resource_type', 'is_active'], name='core_commun_resourc_866579_idx'), models.Index(fields=['is_active'], name='core_commun_is_acti_a2c910_idx'), models.Index(fields=['name'], name='core_commun_name_b0cbe2_idx')],
            },
        ),
    ]
