# Generated by Django 5.2.7 on 2025-11-09 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_communityresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityresource',
            name='hours',
            field=models.JSONField(blank=True, default=dict, help_text="Structured operating hours. Format: {'monday': {'open': '09:00', 'close': '17:00'}, ...}", null=True),
        ),
    ]
