# Generated by Django 5.2.7 on 2025-11-09 20:16

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('FOOD_PANTRY', 'Food Pantry')], help_text='Type of community resource', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('hours', models.JSONField(blank=True, default=dict, help_text="Structured operating hours. Format: {'monday': {'open': '09:00', 'close': '17:00'}, ...}", null=True)),
                ('eligibility_requirements', models.TextField(blank=True, help_text='Eligibility requirements for this resource')),
                ('services', models.TextField(blank=True, help_text='Additional services offered')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this resource is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Community Resources',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['resource_type', 'is_active'], name='mutualaid_c_resourc_846eef_idx'), models.Index(fields=['is_active'], name='mutualaid_c_is_acti_40a074_idx'), models.Index(fields=['name'], name='mutualaid_c_name_e85799_idx')],
            },
        ),
        migrations.CreateModel(
            name='MutualAidPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('OFFER', 'Offer'), ('REQUEST', 'Request')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('FOOD', 'Food'), ('CLOTHING', 'Clothing'), ('SHELTER', 'Shelter'), ('TRANSPORTATION', 'Transportation'), ('OTHER', 'Other')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FULFILLED', 'Fulfilled'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=10)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('contact_info', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mutual_aid_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['type', 'status'], name='mutualaid_m_type_854f07_idx'), models.Index(fields=['category', 'status'], name='mutualaid_m_categor_31dcb2_idx'), models.Index(fields=['created_at'], name='mutualaid_m_created_4e574d_idx')],
            },
        ),
    ]
