# Generated by Django 5.2.7 on 2025-11-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mutualaid', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityresource',
            name='special_hours',
            field=models.TextField(blank=True),
        ),
    ]
